### PR TITLE
Card component

### PR DESCRIPTION
**Pull request by amielmon**
Card component and info stuff

### CODE REVIEW

**Comment by cindy1u0** [comment]
I think the first half got cut off when you resize the screen

**Comment by amielmon** [comment]
> I think the first half got cut off when you resize the screen

There's not a very good way to resize this content due to the nature of the card component

**Comment by amielmon** [comment]
> > I think the first half got cut off when you resize the screen
> 
> There's not a very good way to resize this content due to the nature of the card component

to elaborate the title and link positioning is based around the large font, so scaling stuff might be weird. we can do scrolling or something.

**Comment by amielmon** [comment]
do we want to collapse the cards into a single column when the screen shrinks? kinda like mobile

**Comment by cindy1u0** [comment]
I think so? Maybe we can ask Catherine :DD

**Pull request merged**
