### PR TITLE
Redesign applications page for Spring 2023 recruiting cycle

### PR DESCRIPTION
**Pull request by koulopoulos**
Implements (and extends) the redesign of our applications page :)

### CODE REVIEW

**Comment by dfarooq610** [comment]
image
can we update this to be Project Lead of Faculty Activity Tracker

**Comment by dfarooq610** [comment]
image
this is rendered a bit weirdly and is quite illegible when overlayed over the SVG

**Comment by dfarooq610** [comment]
for clarification's sake:  is this PR to make a visual change, and will another PR open apps formally?

**Comment by koulopoulos** [comment]
> for clarification's sake: is this PR to make a visual change, and will another PR open apps formally?

Yep!

**Comment by koulopoulos** [comment]
> image
> can we update this to be Project Lead of Faculty Activity Tracker

Should be all set now. @dfarooq610

**Comment by koulopoulos** [comment]
> image
> this is rendered a bit weirdly and is quite illegible when overlayed over the SVG

Fixed. @dfarooq610

**Review by dfarooq610 — APPROVED** [review]
Nice job with responsiveness too!

**Comment by koulopoulos** [comment]
And now the styles are breaking for no reason 🙃

**Pull request merged**
